---
- hosts: all
  become: yes

  tasks:

    - name: create docker image using war file
      command: docker build -t tomcatwebbserver:1.0 .
      command: docker run -itd --name tomcatwebbserver -p 8888:8080 tomcatwebbserver:1.0
      args:
        chdir: /dockerimages

    - name: create tag to image
      command: docker tag dockerimages bolajil/dockerimages

    - name: push image on to dockerhub
      command: docker push bolajil/dockerimages

    - name: copy file to destination
      copy:
        src: /var/lib/jenkins/workspace/package/target/ABCtechnologies-1.0.war
        dest: /dockerimages
      tags:
        - simple_copy
      
