---
- hosts: all
  become: yes

  tasks:

    - name: create docker image using war file
      command: docker build -t tomcatwebbserver:1.0 .
      command: docker run -itd --name tomcatwebbserver -p 8888:8080 tomcatwebbserver:1.0
      args:
        chdir: /opt/docker

    - name: create tag to image
      command: docker tag tomcatwebserver bolajil/tomcatwebserver

    - name: push image on to dockerhub
      command: docker push bolajil/tomcatwebserver

    - name: copy file to destination
      copy:
        src: /var/lib/jenkins/workspace/package/target/ABCtechnologies-1.0.war
        dest: /opt/docker
      tags:
        - simple_copy
        
    - name: remove docker images from ansible server
      command: docker rmi tomcat tomcatwebserver:1.0 bolajil/tomcatwebserver
      ignore_errors: yes
      
